DROP TABLE T_LOCATION IF EXISTS;

CREATE TABLE T_LOCATION (
  ID       BIGINT IDENTITY PRIMARY KEY,
  NUMBER   VARCHAR(9)    NOT NULL,
  ADDRESS  VARCHAR(255)  NOT NULL,
  CITY     VARCHAR(255)  NOT NULL,
  COUNTRY  VARCHAR(255)  NOT NULL,
  CURRENCY VARCHAR(3)    NOT NULL,
  NAME     VARCHAR(255)  NOT NULL,
  PRICE    DECIMAL(4, 2) NOT NULL,
  STATE    VARCHAR(255)  NOT NULL,
  zip      VARCHAR(255)  NOT NULL,
  UNIQUE (NUMBER)
);

ALTER TABLE T_LOCATION
  ALTER COLUMN PRICE SET DEFAULT 0.0;
